name: Stagin BE workflow

on:
  push:
    branches:
      - staging
    paths:
      - packages/backend/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/backend

    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        run: |
          docker build -t read-line-be-image --build-arg FRONTEND_URL=$FRONTEND_URL packeges/backend
          heroku container:push -a read-line-be web

      - name: Realease
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a read-line-be web
